// <auto-generated />
using System;
using GInvent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GInvent.Migrations
{
    [DbContext(typeof(GInventDbContext))]
    partial class GInventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GInvent.Models.Movimiento", b =>
                {
                    b.Property<int>("idMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProductoidProducto")
                        .HasColumnType("int");

                    b.Property<int?>("cantidadMovimiento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tipoMovimiento")
                        .HasColumnType("longtext");

                    b.HasKey("idMovimiento");

                    b.HasIndex("ProductoidProducto");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("GInvent.Models.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProveedoridProveedor")
                        .HasColumnType("int");

                    b.Property<string>("nombreProducto")
                        .HasColumnType("longtext");

                    b.Property<double?>("precioProducto")
                        .HasColumnType("double");

                    b.Property<int?>("stockProducto")
                        .HasColumnType("int");

                    b.HasKey("idProducto");

                    b.HasIndex("ProveedoridProveedor");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GInvent.Models.Proveedor", b =>
                {
                    b.Property<int>("idProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("contactoProveedor")
                        .HasColumnType("longtext");

                    b.Property<string>("nombreProveedor")
                        .HasColumnType("longtext");

                    b.HasKey("idProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GInvent.Models.Movimiento", b =>
                {
                    b.HasOne("GInvent.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoidProducto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GInvent.Models.Producto", b =>
                {
                    b.HasOne("GInvent.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedoridProveedor");

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
